import type { Metadata } from 'next';
import { AskChat } from '@/components/AskChat';

export const metadata: Metadata = {
  title: 'Ask',
  description:
    'Ask questions about the Speedcube Ratings codebase. Answers come from the Devin MCP server, grounded in this repository.',
  robots: { index: false, follow: false },
};

export default function AskPage() {
  return (
    <div className="mx-auto max-w-[900px] px-4 sm:px-8 pt-10 pb-16">
      <header className="mb-6">
        <h1
          className="font-display text-[2.25rem] sm:text-[2.75rem] leading-none tracking-[-0.03em] text-[var(--color-ink)]"
          style={{ fontVariationSettings: '"opsz" 144, "SOFT" 40, "wght" 520' }}
        >
          Ask
        </h1>
        <p className="eyebrow mt-2">
          Questions about this repository · answered by Devin
        </p>
        <p className="mt-4 text-[14px] leading-relaxed text-[var(--color-muted)] max-w-[64ch]">
          Ask anything about how Speedcube Ratings works — the ingest pipeline,
          the rating model, the web app. Responses are generated by the{' '}
          <a
            href="https://docs.devin.ai/work-with-devin/devin-mcp"
            className="ink-link"
            target="_blank"
            rel="noopener noreferrer"
          >
            Devin MCP
          </a>{' '}
          server using this repository as context. No other sources.
        </p>
      </header>
      <AskChat />
    </div>
  );
}
